functionsDirectory = "C:\\Users\\mille\\GItHub Projects\\Mini-Project-3-Chat-Interface\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\mille\\GItHub Projects\\Mini-Project-3-Chat-Interface"
publishOrigin = "default"
functions = "C:\\Users\\mille\\GItHub Projects\\Mini-Project-3-Chat-Interface\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]